### ISSUE TITLE
Common - Header - Navigation bar

### ISSUE THREAD

**Issue by Tony-T-R-A-N** [TechEveryday/techeveryday.github.io#1]
**Acceptance criteria**: As a user, I want to be able to navigate, so that I can view content.

### Task(s):
- [ ] "Our Services" link to navigate to placeholder page
- [ ] "Our Products" link to navigate to placeholder page
- [ ] "About Us" link to navigate to placeholder page
- [ ] "Contact Us" link to navigate to placeholder page

### Screenshot(s):
![Image](https://github.com/TechEveryday/techeveryday.github.io/assets/36994775/90379c1e-fdbd-4f8b-8d8d-101763480831)

### Link(s):
* [Figma](https://www.figma.com/file/xdUAywzFmhkpD9Wy7jENII/TE-Website%2FCashcow?type=whiteboard&node-id=0-1)
* [Website](https://www.tech-everyday.com/)
